### ISSUE TITLE
Head requests received as GET by the mock/stub server

### ISSUE THREAD

**Issue by avishai-ish-shalom** [wix/wix-http-testkit#37]
This test fails
```
    "support head requests" in new ctx {
      head("/")
      server must receivedAnyRequestThat(beHead)
    }
```

This seems to be an akka http server issue, not the client. Probably related to the `akka.http.server.transparent-head-requests` config as explained [here](https://github.com/akka/akka/issues/18020)

**Comment by noam-almog** [comment]
resolved
