### ISSUE TITLE
Be able to use WixJsonMarshaller with custom object mapper

### ISSUE THREAD

**Issue by igorynia** [wix/wix-http-testkit#41]
Hi! Our team is currently in progress of making a shift from spray to the test kit and we want to say thank you for a great effort! However, while doing a refactoring, I found a few issues, that I can't create my own WixJsonMarshaller with custom object mapper, but we do use custom one in our code. It would be great to be able to construct WixJsonMarshaller, passing objectMapper in the constructor.
You can see an example how I did that here https://github.com/wix-private/wix-ecommerce-server/pull/386/files#diff-a3b74c8ec1eb524f74004f2e81fbb1a1R25. If you want, I would be glad submit a PR with the fix. Also, I will open another ticket about the other small issue I've found.

**Comment by noam-almog** [comment]
the testkit jackson marshaller have a configure method that allow you to configure the object mapper [https://github.com/wix/wix-http-testkit/blob/master/http-testkit-marshaller-jackson/src/main/scala/com/wix/e2e/http/json/JsonJacksonMarshaller.scala#L20](see)
I will take a look at what we did on WixMarshaller and see if we can expose something for you too

**Comment by noam-almog** [comment]
@nadavwe this issue should be open on the FW side, not on this repo
