### ISSUE TITLE
WixHttpTestkitResources.xmlPrinter is not thread-safe and thus can’t be shared

### ISSUE THREAD

**Issue by igorynia** [wix/wix-http-testkit#42]
Hi! While doing a shift from spray to akka-http I found one small issue, calling:
```
HttpClientRequestBodyTransformers#withPayload(xml: Node): RequestTransformer
```
in multi-threaded test env, this method uses `WixHttpTestkitResources.xmlPrinter`, implementation of which is not thread-safe and thus can't be a shared variable. I would propose changing the definition of `xmlPrinter` from `lazy val` to `def` or inlining it here since there is only one use of it. If you would like I can open a PR.

**Comment by noam-almog** [comment]
@igorynia did you actually hit a bug or you are just speculating ?

**Comment by igorynia** [comment]
@noam-almog yes I did, adding `sequential` to the suite helped me, but others could also hit this in the future.

**Comment by noam-almog** [comment]
how do you suggest we solve this ?

**Comment by igorynia** [comment]
Change the definition of `WixHttpTestkitResources .xmlPrinter` from lazy val to def or inlint it :). I can do the fix and open a PR

**Comment by noam-almog** [comment]
fixed
