### ISSUE TITLE
Stub server doesn't support chunked entity on request

### ISSUE THREAD

**Issue by l3lik** [wix/wix-http-testkit#47]
Create a stub server, send request with chunked entity.
The verification of recorded request entity against the original fails.

**Comment by l3lik** [comment]
package com.wix.wixcode.dispatcher

import akka.http.scaladsl.model.{HttpResponse, StatusCodes}
import com.wix.cloud.commons.http.{HttpClient, HttpMethods, Response}
import com.wix.e2e.http.RequestHandler
import com.wix.e2e.http.api.StubWebServer
import com.wix.e2e.http.matchers.RequestMatchers
import com.wix.e2e.http.server.WebServerFactory.aStubWebServer
import com.wix.hoopoe.http.testkit.EmbeddedHttpProbe
import org.apache.http.entity.ContentType
import org.specs2.matcher.Matcher
import org.specs2.mutable.SpecificationWithJUnit
import org.specs2.specification.Scope
import spray.http.HttpCharsets.`UTF-8`
import spray.http.HttpRequest

import scala.concurrent.Await
import scala.concurrent.duration.Duration
import scala.concurrent.ExecutionContext.Implicits._

class ProbeTest extends SpecificationWithJUnit {

  "probe" should {
    "contain chunked entity in request" in new Context {
      givenHttpProbe(probe)

      sendRequest(8080)

      probe.requests.head must havePayload("lala")
    }
  }

  "stubServer" should {
    "contain chunked entity in request" in new Context {
      givenAStubServer(stubServer)

      sendRequest(8081)

      stubServer.recordedRequests.head must RequestMatchers.haveBodyWith("lala")
    }
  }

  trait Context extends Scope with RequestMatchers {
    val probe = new EmbeddedHttpProbe(8080, defaultHandler = EmbeddedHttpProbe.NotImplementedHandler)

    val handler: RequestHandler = {
      case _ => HttpResponse(status = StatusCodes.NotImplemented)
    }
    val stubServer: StubWebServer = aStubWebServer.onPort(8081).build
    stubServer.appendAll(handler)
  }

  def givenAStubServer(stubWebServer: StubWebServer) = stubWebServer.start()

  def givenHttpProbe(probe: EmbeddedHttpProbe) = probe.doStart()

  def sendRequest(port: Int): Response =
    Await.result(HttpClient(1)
      .request(s"http://localhost:$port", HttpMethods.POST)
      .withBody("lala", ContentType.DEFAULT_TEXT)
      .withChunked
      .send, Duration.Inf)

  def havePayload(payload: String): Matcher[HttpRequest] = ===(payload) ^^ extractEntityAsString

  private def extractEntityAsString: HttpRequest => String = _.entity.asString(`UTF-8`)
}

**Comment by l3lik** [comment]
`import akka.http.scaladsl.model.{HttpResponse, StatusCodes}
import com.wix.cloud.commons.http.{HttpClient, HttpMethods, Response}
import com.wix.e2e.http.RequestHandler
import com.wix.e2e.http.api.StubWebServer
import com.wix.e2e.http.matchers.RequestMatchers
import com.wix.e2e.http.server.WebServerFactory.aStubWebServer
import com.wix.hoopoe.http.testkit.EmbeddedHttpProbe
import org.apache.http.entity.ContentType
import org.specs2.matcher.Matcher
import org.specs2.mutable.SpecificationWithJUnit
import org.specs2.specification.Scope
import spray.http.HttpCharsets.`UTF-8`
import spray.http.HttpRequest

import scala.concurrent.Await
import scala.concurrent.duration.Duration
import scala.concurrent.ExecutionContext.Implicits._

class ProbeTest extends SpecificationWithJUnit {

  "probe" should {
    "contain chunked entity in request" in new Context {
      givenHttpProbe(probe)

      sendRequest(8080)

      probe.requests.head must havePayload("lala")
    }
  }

  "stubServer" should {
    "contain chunked entity in request" in new Context {
      givenAStubServer(stubServer)

      sendRequest(8081)

      stubServer.recordedRequests.head must RequestMatchers.haveBodyWith("lala")
    }
  }

  trait Context extends Scope with RequestMatchers {
    val probe = new EmbeddedHttpProbe(8080, defaultHandler = EmbeddedHttpProbe.NotImplementedHandler)

    val handler: RequestHandler = {
      case _ => HttpResponse(status = StatusCodes.NotImplemented)
    }
    val stubServer: StubWebServer = aStubWebServer.onPort(8081).build
    stubServer.appendAll(handler)
  }

  def givenAStubServer(stubWebServer: StubWebServer) = stubWebServer.start()

  def givenHttpProbe(probe: EmbeddedHttpProbe) = probe.doStart()

  def sendRequest(port: Int): Response =
    Await.result(HttpClient(1)
      .request(s"http://localhost:$port", HttpMethods.POST)
      .withBody("lala", ContentType.DEFAULT_TEXT)
      .withChunked
      .send, Duration.Inf)

  def havePayload(payload: String): Matcher[HttpRequest] = ===(payload) ^^ extractEntityAsString

  private def extractEntityAsString: HttpRequest => String = _.entity.asString(`UTF-8`)
}`

**Comment by noam-almog** [comment]
@l3lik stub server is writing the data properly, the main problem is that it's not that obvious to extract data from chunks, reading documentation now to figure this out and have a proper extractor to allow you to do that.

**Comment by noam-almog** [comment]
resolved on 0.1.11
