### ISSUE TITLE
waitFor in BlockingRequestManager should not be inifinite

### ISSUE THREAD

**Issue by dkarlinsky** [wix/wix-http-testkit#58]
On [this line](https://github.com/wix/wix-http-testkit/blob/4a8d69de3306ff665fdfa47ded3fab1c99126ea3/http-testkit-client/src/main/scala/com/wix/e2e/http/client/internals/RequestManager.scala#L63) the await timeout for the future is set to `Duration.Inf`, which assumes that `akka-http` will honor the request timeout passed to it (`withTimeout`).
Unfortunately sometimes there are bugs in `akka-http` and the future may never be fulfilled.
This happened in `akka-http 10.1.0-RC1`.
It is better for future await to be limited to `withTimeout` as well (or slightly longer).

**Comment by noam-almog** [comment]
merged, thanks 👍
